 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// solutionPath:            <solution>
// projectPath:             <solution>\Sparkle.Data
// projectName:             Sparkle.Data

// codegen: getting list of interfaces from files in project path
// codegen: found 0 interfaces

// codegen: getting list of interfaces from compiled assembly
// codegen: file found <solution>\Sparkle.Data\bin\debug\Sparkle.Data.dll
// codegen: loading assembly and its dependencies: Sparkle.Infrastructure, Sparkle.Entities, Sparkle.Data
// codegen: repository attribute type is Sparkle.Data.RepositoryAttribute, Sparkle.Data, Version=1.0.0.140, Culture=neutral, PublicKeyToken=null
// codegen: assembly loaded with 207 public types

namespace Sparkle.Data.Networks
{
    using System;

// codegen: writing factory interface
	
    /// <summary>
    /// Provides access to all data access repositories.
    /// </summary>
    public partial interface IRepositoryFactory : IDisposable
    {
		IAchievementsRepository Achievements { get; }
		IAchievementsCompaniesRepository AchievementsCompanies { get; }
		IAchievementsUsersRepository AchievementsUsers { get; }
		IActivitiesRepository Activities { get; }
		IAdsRepository Ads { get; }
		IAdsCategoriesRepository AdsCategories { get; }
		IAdTagsRepository AdTags { get; }
		IAlbumsRepository Albums { get; }
		IApiKeysRepository ApiKeys { get; }
		IApplyRequestsRepository ApplyRequests { get; }
		IBuildingRepository Building { get; }
		ICareerOpportunitiesRepository CareerOpportunities { get; }
		IClubsRepository Clubs { get; }
		ICompanyRepository Companies { get; }
		ICompaniesSkillsRepository CompaniesSkills { get; }
		ICompaniesVisitsRepository CompaniesVisits { get; }
		ICompanyAdminRepository CompanyAdmin { get; }
		ICompanyCategoriesRepository CompanyCategories { get; }
		ICompanyContactsRepository CompanyContacts { get; }
		ICompanyPlacesRepository CompanyPlaces { get; }
		ICompanyProfileFieldsRepository CompanyProfileFields { get; }
		ICompanyRelationshipsRepository CompanyRelationships { get; }
		ICompanyRelationshipTypesRepository CompanyRelationshipTypes { get; }
		ICompanyRequestMessagesRepository CompanyRequestMessages { get; }
		ICompanyRequestsRepository CompanyRequests { get; }
		ICompanyTagsRepository CompanyTags { get; }
		ICreateNetworkRequestsRepository CreateNetworkRequests { get; }
		IDeviceConfigurationRepository DeviceConfiguration { get; }
		IDevicePlanningRepository DevicePlanning { get; }
		IDevicesRepository Devices { get; }
		IEmailMessagesRepository EmailMessages { get; }
		IEventPublicMembersRepository EventPublicMembers { get; }
		IEventsRepository Events { get; }
		IEventsCategoriesRepository EventsCategories { get; }
		IEventsMembersRepository EventsMembers { get; }
		IExchangeMaterialsRepository ExchangeMaterials { get; }
		IExchangeSkillsRepository ExchangeSkills { get; }
		IExchangeSurfacesRepository ExchangeSurfaces { get; }
		IFriendsRepository Friends { get; }
		IGroupsRepository Groups { get; }
		IGroupsCategoriesRepository GroupsCategories { get; }
		IGroupsInterestsRepository GroupsInterests { get; }
		IGroupsMembersRepository GroupsMembers { get; }
		IGroupsRecreationsRepository GroupsRecreations { get; }
		IGroupsSkillsRepository GroupsSkills { get; }
		IGroupTagsRepository GroupTags { get; }
		IHintsRepository Hints { get; }
		IHintsToUsersRepository HintsToUsers { get; }
		IInboundEmailMessageRepository InboundEmailMessage { get; }
		IInformationNotesRepository InformationNotes { get; }
		IInterestsRepository Interests { get; }
		IInvitedRepository Invited { get; }
		IJobRepository Job { get; }
		ILinksRepository Links { get; }
		ILiveRepository Live { get; }
		ILostItemsRepository LostItems { get; }
		IMembershipRepository Membership { get; }
		IMenusRepository Menus { get; }
		IMenusPlanningRepository MenusPlanning { get; }
		INetworksRepository Networks { get; }
		INetworkTypesRepository NetworkTypes { get; }
		INotificationsRepository Notifications { get; }
		INumbersRepository Numbers { get; }
		IPagesRepository Pages { get; }
		IPartnerResourceProfileFieldsRepository PartnerResourceProfileFields { get; }
		IPartnerResourcesRepository PartnerResources { get; }
		IPartnerResourceTagsRepository PartnerResourceTags { get; }
		IPeopleRepository People { get; }
		IPeoplesInterestsRepository PeoplesInterests { get; }
		IPeoplesRecreationsRepository PeoplesRecreations { get; }
		IPeoplesSkillsRepository PeoplesSkills { get; }
		IPeopleVisitsRepository PeopleVisits { get; }
		IPicturesRepository Pictures { get; }
		IPlaceProfileFieldsRepository PlaceProfileFields { get; }
		IPlacesRepository Places { get; }
		IPlacesCategoriesRepository PlacesCategories { get; }
		IPlacesHistoryRepository PlacesHistory { get; }
		IPollsRepository Polls { get; }
		IPollsAnswersRepository PollsAnswers { get; }
		IPollsChoicesRepository PollsChoices { get; }
		IPrivateMessageRepository PrivateMessage { get; }
		IProfileFieldsRepository ProfileFields { get; }
		IProfileFieldsAvailiableValuesRepository ProfileFieldsAvailiableValues { get; }
		IProjectsRepository Projects { get; }
		IProjectsMembersRepository ProjectsMembers { get; }
		IRecreationsRepository Recreations { get; }
		IRegisterRequestsRepository RegisterRequests { get; }
		IRelationshipRepository Relationship { get; }
		IRequestsForProposalRepository RequestsForProposal { get; }
		IResumesRepository Resumes { get; }
		IResumesSkillsRepository ResumesSkills { get; }
		ISeekFriendsRepository SeekFriends { get; }
		ISkillsRepository Skills { get; }
		ISocialNetworkCompanySubscriptionsRepository SocialNetworkCompanySubscriptions { get; }
		ISocialNetworkConnectionsRepository SocialNetworkConnections { get; }
		ISocialNetworkStatesRepository SocialNetworkStates { get; }
		ISocialNetworkUserSubscriptionsRepository SocialNetworkUserSubscriptions { get; }
		IStatsCounterHitsRepository StatsCounterHits { get; }
		IStatsCountersRepository StatsCounters { get; }
		IStripeTransactionsRepository StripeTransactions { get; }
		ISubscriptionNotificationsRepository SubscriptionNotifications { get; }
		ISubscriptionsRepository Subscriptions { get; }
		ISubscriptionTemplatesRepository SubscriptionTemplates { get; }
		ITagCategoriesRepository TagCategories { get; }
		ITagDefinitionsRepository TagDefinitions { get; }
		ITeamsRepository Teams { get; }
		ITeamsMembersRepository TeamsMembers { get; }
		ITextRepository Text { get; }
		ITimelineItemCommentLikesRepository TimelineItemCommentLikes { get; }
		ITimelineItemLikesRepository TimelineItemLikes { get; }
		ITimelineItemSkillsRepository TimelineItemSkills { get; }
		ITimelineItemTagsRepository TimelineItemTags { get; }
		ITouchCommunicationItemsRepository TouchCommunicationItems { get; }
		ITouchCommunicationsRepository TouchCommunications { get; }
		IUserActionKeysRepository UserActionKeys { get; }
		IUserEmailChangeRequestRepository UserEmailChangeRequest { get; }
		IUserPresencesRepository UserPresences { get; }
		IUserProfileFieldsRepository UserProfileFields { get; }
		IUserSettingsRepository UserSettings { get; }
		IUserTagsRepository UserTags { get; }
		IWallRepository Wall { get; }
		IWallCommentsRepository WallComments { get; }
    }
	
// codegen: writing factory class
	/*
    public partial class RepositoryFactory : IRepositoryFactory
    {
		IAchievementsRepository IRepositoryFactory.Achievements { get { return this.provider.Achievements; } }
		IAchievementsCompaniesRepository IRepositoryFactory.AchievementsCompanies { get { return this.provider.AchievementsCompanies; } }
		IAchievementsUsersRepository IRepositoryFactory.AchievementsUsers { get { return this.provider.AchievementsUsers; } }
		IActivitiesRepository IRepositoryFactory.Activities { get { return this.provider.Activities; } }
		IAdsRepository IRepositoryFactory.Ads { get { return this.provider.Ads; } }
		IAdsCategoriesRepository IRepositoryFactory.AdsCategories { get { return this.provider.AdsCategories; } }
		IAdTagsRepository IRepositoryFactory.AdTags { get { return this.provider.AdTags; } }
		IAlbumsRepository IRepositoryFactory.Albums { get { return this.provider.Albums; } }
		IApiKeysRepository IRepositoryFactory.ApiKeys { get { return this.provider.ApiKeys; } }
		IApplyRequestsRepository IRepositoryFactory.ApplyRequests { get { return this.provider.ApplyRequests; } }
		IBuildingRepository IRepositoryFactory.Building { get { return this.provider.Building; } }
		ICareerOpportunitiesRepository IRepositoryFactory.CareerOpportunities { get { return this.provider.CareerOpportunities; } }
		IClubsRepository IRepositoryFactory.Clubs { get { return this.provider.Clubs; } }
		ICompanyRepository IRepositoryFactory.Companies { get { return this.provider.Companies; } }
		ICompaniesSkillsRepository IRepositoryFactory.CompaniesSkills { get { return this.provider.CompaniesSkills; } }
		ICompaniesVisitsRepository IRepositoryFactory.CompaniesVisits { get { return this.provider.CompaniesVisits; } }
		ICompanyAdminRepository IRepositoryFactory.CompanyAdmin { get { return this.provider.CompanyAdmin; } }
		ICompanyCategoriesRepository IRepositoryFactory.CompanyCategories { get { return this.provider.CompanyCategories; } }
		ICompanyContactsRepository IRepositoryFactory.CompanyContacts { get { return this.provider.CompanyContacts; } }
		ICompanyPlacesRepository IRepositoryFactory.CompanyPlaces { get { return this.provider.CompanyPlaces; } }
		ICompanyProfileFieldsRepository IRepositoryFactory.CompanyProfileFields { get { return this.provider.CompanyProfileFields; } }
		ICompanyRelationshipsRepository IRepositoryFactory.CompanyRelationships { get { return this.provider.CompanyRelationships; } }
		ICompanyRelationshipTypesRepository IRepositoryFactory.CompanyRelationshipTypes { get { return this.provider.CompanyRelationshipTypes; } }
		ICompanyRequestMessagesRepository IRepositoryFactory.CompanyRequestMessages { get { return this.provider.CompanyRequestMessages; } }
		ICompanyRequestsRepository IRepositoryFactory.CompanyRequests { get { return this.provider.CompanyRequests; } }
		ICompanyTagsRepository IRepositoryFactory.CompanyTags { get { return this.provider.CompanyTags; } }
		ICreateNetworkRequestsRepository IRepositoryFactory.CreateNetworkRequests { get { return this.provider.CreateNetworkRequests; } }
		IDeviceConfigurationRepository IRepositoryFactory.DeviceConfiguration { get { return this.provider.DeviceConfiguration; } }
		IDevicePlanningRepository IRepositoryFactory.DevicePlanning { get { return this.provider.DevicePlanning; } }
		IDevicesRepository IRepositoryFactory.Devices { get { return this.provider.Devices; } }
		IEmailMessagesRepository IRepositoryFactory.EmailMessages { get { return this.provider.EmailMessages; } }
		IEventPublicMembersRepository IRepositoryFactory.EventPublicMembers { get { return this.provider.EventPublicMembers; } }
		IEventsRepository IRepositoryFactory.Events { get { return this.provider.Events; } }
		IEventsCategoriesRepository IRepositoryFactory.EventsCategories { get { return this.provider.EventsCategories; } }
		IEventsMembersRepository IRepositoryFactory.EventsMembers { get { return this.provider.EventsMembers; } }
		IExchangeMaterialsRepository IRepositoryFactory.ExchangeMaterials { get { return this.provider.ExchangeMaterials; } }
		IExchangeSkillsRepository IRepositoryFactory.ExchangeSkills { get { return this.provider.ExchangeSkills; } }
		IExchangeSurfacesRepository IRepositoryFactory.ExchangeSurfaces { get { return this.provider.ExchangeSurfaces; } }
		IFriendsRepository IRepositoryFactory.Friends { get { return this.provider.Friends; } }
		IGroupsRepository IRepositoryFactory.Groups { get { return this.provider.Groups; } }
		IGroupsCategoriesRepository IRepositoryFactory.GroupsCategories { get { return this.provider.GroupsCategories; } }
		IGroupsInterestsRepository IRepositoryFactory.GroupsInterests { get { return this.provider.GroupsInterests; } }
		IGroupsMembersRepository IRepositoryFactory.GroupsMembers { get { return this.provider.GroupsMembers; } }
		IGroupsRecreationsRepository IRepositoryFactory.GroupsRecreations { get { return this.provider.GroupsRecreations; } }
		IGroupsSkillsRepository IRepositoryFactory.GroupsSkills { get { return this.provider.GroupsSkills; } }
		IGroupTagsRepository IRepositoryFactory.GroupTags { get { return this.provider.GroupTags; } }
		IHintsRepository IRepositoryFactory.Hints { get { return this.provider.Hints; } }
		IHintsToUsersRepository IRepositoryFactory.HintsToUsers { get { return this.provider.HintsToUsers; } }
		IInboundEmailMessageRepository IRepositoryFactory.InboundEmailMessage { get { return this.provider.InboundEmailMessage; } }
		IInformationNotesRepository IRepositoryFactory.InformationNotes { get { return this.provider.InformationNotes; } }
		IInterestsRepository IRepositoryFactory.Interests { get { return this.provider.Interests; } }
		IInvitedRepository IRepositoryFactory.Invited { get { return this.provider.Invited; } }
		IJobRepository IRepositoryFactory.Job { get { return this.provider.Job; } }
		ILinksRepository IRepositoryFactory.Links { get { return this.provider.Links; } }
		ILiveRepository IRepositoryFactory.Live { get { return this.provider.Live; } }
		ILostItemsRepository IRepositoryFactory.LostItems { get { return this.provider.LostItems; } }
		IMembershipRepository IRepositoryFactory.Membership { get { return this.provider.Membership; } }
		IMenusRepository IRepositoryFactory.Menus { get { return this.provider.Menus; } }
		IMenusPlanningRepository IRepositoryFactory.MenusPlanning { get { return this.provider.MenusPlanning; } }
		INetworksRepository IRepositoryFactory.Networks { get { return this.provider.Networks; } }
		INetworkTypesRepository IRepositoryFactory.NetworkTypes { get { return this.provider.NetworkTypes; } }
		INotificationsRepository IRepositoryFactory.Notifications { get { return this.provider.Notifications; } }
		INumbersRepository IRepositoryFactory.Numbers { get { return this.provider.Numbers; } }
		IPagesRepository IRepositoryFactory.Pages { get { return this.provider.Pages; } }
		IPartnerResourceProfileFieldsRepository IRepositoryFactory.PartnerResourceProfileFields { get { return this.provider.PartnerResourceProfileFields; } }
		IPartnerResourcesRepository IRepositoryFactory.PartnerResources { get { return this.provider.PartnerResources; } }
		IPartnerResourceTagsRepository IRepositoryFactory.PartnerResourceTags { get { return this.provider.PartnerResourceTags; } }
		IPeopleRepository IRepositoryFactory.People { get { return this.provider.People; } }
		IPeoplesInterestsRepository IRepositoryFactory.PeoplesInterests { get { return this.provider.PeoplesInterests; } }
		IPeoplesRecreationsRepository IRepositoryFactory.PeoplesRecreations { get { return this.provider.PeoplesRecreations; } }
		IPeoplesSkillsRepository IRepositoryFactory.PeoplesSkills { get { return this.provider.PeoplesSkills; } }
		IPeopleVisitsRepository IRepositoryFactory.PeopleVisits { get { return this.provider.PeopleVisits; } }
		IPicturesRepository IRepositoryFactory.Pictures { get { return this.provider.Pictures; } }
		IPlaceProfileFieldsRepository IRepositoryFactory.PlaceProfileFields { get { return this.provider.PlaceProfileFields; } }
		IPlacesRepository IRepositoryFactory.Places { get { return this.provider.Places; } }
		IPlacesCategoriesRepository IRepositoryFactory.PlacesCategories { get { return this.provider.PlacesCategories; } }
		IPlacesHistoryRepository IRepositoryFactory.PlacesHistory { get { return this.provider.PlacesHistory; } }
		IPollsRepository IRepositoryFactory.Polls { get { return this.provider.Polls; } }
		IPollsAnswersRepository IRepositoryFactory.PollsAnswers { get { return this.provider.PollsAnswers; } }
		IPollsChoicesRepository IRepositoryFactory.PollsChoices { get { return this.provider.PollsChoices; } }
		IPrivateMessageRepository IRepositoryFactory.PrivateMessage { get { return this.provider.PrivateMessage; } }
		IProfileFieldsRepository IRepositoryFactory.ProfileFields { get { return this.provider.ProfileFields; } }
		IProfileFieldsAvailiableValuesRepository IRepositoryFactory.ProfileFieldsAvailiableValues { get { return this.provider.ProfileFieldsAvailiableValues; } }
		IProjectsRepository IRepositoryFactory.Projects { get { return this.provider.Projects; } }
		IProjectsMembersRepository IRepositoryFactory.ProjectsMembers { get { return this.provider.ProjectsMembers; } }
		IRecreationsRepository IRepositoryFactory.Recreations { get { return this.provider.Recreations; } }
		IRegisterRequestsRepository IRepositoryFactory.RegisterRequests { get { return this.provider.RegisterRequests; } }
		IRelationshipRepository IRepositoryFactory.Relationship { get { return this.provider.Relationship; } }
		IRequestsForProposalRepository IRepositoryFactory.RequestsForProposal { get { return this.provider.RequestsForProposal; } }
		IResumesRepository IRepositoryFactory.Resumes { get { return this.provider.Resumes; } }
		IResumesSkillsRepository IRepositoryFactory.ResumesSkills { get { return this.provider.ResumesSkills; } }
		ISeekFriendsRepository IRepositoryFactory.SeekFriends { get { return this.provider.SeekFriends; } }
		ISkillsRepository IRepositoryFactory.Skills { get { return this.provider.Skills; } }
		ISocialNetworkCompanySubscriptionsRepository IRepositoryFactory.SocialNetworkCompanySubscriptions { get { return this.provider.SocialNetworkCompanySubscriptions; } }
		ISocialNetworkConnectionsRepository IRepositoryFactory.SocialNetworkConnections { get { return this.provider.SocialNetworkConnections; } }
		ISocialNetworkStatesRepository IRepositoryFactory.SocialNetworkStates { get { return this.provider.SocialNetworkStates; } }
		ISocialNetworkUserSubscriptionsRepository IRepositoryFactory.SocialNetworkUserSubscriptions { get { return this.provider.SocialNetworkUserSubscriptions; } }
		IStatsCounterHitsRepository IRepositoryFactory.StatsCounterHits { get { return this.provider.StatsCounterHits; } }
		IStatsCountersRepository IRepositoryFactory.StatsCounters { get { return this.provider.StatsCounters; } }
		IStripeTransactionsRepository IRepositoryFactory.StripeTransactions { get { return this.provider.StripeTransactions; } }
		ISubscriptionNotificationsRepository IRepositoryFactory.SubscriptionNotifications { get { return this.provider.SubscriptionNotifications; } }
		ISubscriptionsRepository IRepositoryFactory.Subscriptions { get { return this.provider.Subscriptions; } }
		ISubscriptionTemplatesRepository IRepositoryFactory.SubscriptionTemplates { get { return this.provider.SubscriptionTemplates; } }
		ITagCategoriesRepository IRepositoryFactory.TagCategories { get { return this.provider.TagCategories; } }
		ITagDefinitionsRepository IRepositoryFactory.TagDefinitions { get { return this.provider.TagDefinitions; } }
		ITeamsRepository IRepositoryFactory.Teams { get { return this.provider.Teams; } }
		ITeamsMembersRepository IRepositoryFactory.TeamsMembers { get { return this.provider.TeamsMembers; } }
		ITextRepository IRepositoryFactory.Text { get { return this.provider.Text; } }
		ITimelineItemCommentLikesRepository IRepositoryFactory.TimelineItemCommentLikes { get { return this.provider.TimelineItemCommentLikes; } }
		ITimelineItemLikesRepository IRepositoryFactory.TimelineItemLikes { get { return this.provider.TimelineItemLikes; } }
		ITimelineItemSkillsRepository IRepositoryFactory.TimelineItemSkills { get { return this.provider.TimelineItemSkills; } }
		ITimelineItemTagsRepository IRepositoryFactory.TimelineItemTags { get { return this.provider.TimelineItemTags; } }
		ITouchCommunicationItemsRepository IRepositoryFactory.TouchCommunicationItems { get { return this.provider.TouchCommunicationItems; } }
		ITouchCommunicationsRepository IRepositoryFactory.TouchCommunications { get { return this.provider.TouchCommunications; } }
		IUserActionKeysRepository IRepositoryFactory.UserActionKeys { get { return this.provider.UserActionKeys; } }
		IUserEmailChangeRequestRepository IRepositoryFactory.UserEmailChangeRequest { get { return this.provider.UserEmailChangeRequest; } }
		IUserPresencesRepository IRepositoryFactory.UserPresences { get { return this.provider.UserPresences; } }
		IUserProfileFieldsRepository IRepositoryFactory.UserProfileFields { get { return this.provider.UserProfileFields; } }
		IUserSettingsRepository IRepositoryFactory.UserSettings { get { return this.provider.UserSettings; } }
		IUserTagsRepository IRepositoryFactory.UserTags { get { return this.provider.UserTags; } }
		IWallRepository IRepositoryFactory.Wall { get { return this.provider.Wall; } }
		IWallCommentsRepository IRepositoryFactory.WallComments { get { return this.provider.WallComments; } }
    }
	*/
}

// codegen: ended
