 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// solutionPath:            <solution>
// projectPath:             <solution>\Networks
// projectName:             Networks


namespace Sparkle.Services.Networks
{
    using System;
    using Sparkle.Infrastructure;
    using Sparkle.Data.Networks;
    using Sparkle.UI;

    public partial interface IServiceFactory : IDisposable
    {
		HostingEnvironment                        HostingEnvironment                { get; set; }
		Strings                                   Lang                              { get; }
		ILogger                                   Logger                            { get; set; }
		IEmailTemplateProvider                    EmailTemplateProvider             { get; set; }
		IRepositoryFactory                        Repositories                      { get; set; }
		Application                               Application                       { get; set; }
		AppConfiguration                          AppConfiguration                  { get; set; }

		IAchievementsCompanyService               AchievementsCompany               { get; }
		IAchievementsService                      Achievements                      { get; }
		IAchievementsUsersService                 AchievementsUsers                 { get; }
		IActivitiesService                        Activities                        { get; }
		IAdsCategoriesService                     AdsCategories                     { get; }
		IAdsService                               Ads                               { get; }
		IAlbumsService                            Albums                            { get; }
		IApiKeysService                           ApiKeys                           { get; }
		IBuildingService                          Building                          { get; }
		ICareerOpportunitiesService               CareerOpportunities               { get; }
		IClubsService                             Clubs                             { get; }
		ICompaniesVisitsService                   CompaniesVisits                   { get; }
		ICompanyAdminService                      CompanyAdmin                      { get; }
		ICompanyContactsService                   CompanyContacts                   { get; }
		ICompanyRelationshipsService              CompanyRelationships              { get; }
		ICompanyService                           Company                           { get; }
		ICompanySkillsService                     CompanySkills                     { get; }
		ICreateNetworkRequestsService             CreateNetworkRequests             { get; }
		ICryptoService                            Crypto                            { get; }
		IDeviceConfigurationService               DeviceConfiguration               { get; }
		IDevicePlanningService                    DevicePlanning                    { get; }
		IDevicesService                           Devices                           { get; }
		IEmailMessagesService                     EmailMessages                     { get; }
		IEmailService                             Email                             { get; }
		IEventPublicMembersService                EventPublicMembers                { get; }
		IEventsCategoriesService                  EventsCategories                  { get; }
		IEventsMembersService                     EventsMembers                     { get; }
		IEventsService                            Events                            { get; }
		IExchangeMaterialsService                 ExchangeMaterials                 { get; }
		IExchangeSkillsService                    ExchangeSkills                    { get; }
		IExchangeSurfacesService                  ExchangeSurfaces                  { get; }
		IFriendService                            Friend                            { get; }
		IGroupsCategoriesService                  GroupsCategories                  { get; }
		IGroupsMembersService                     GroupsMembers                     { get; }
		IGroupsService                            Groups                            { get; }
		IGroupsTagsService                        GroupsTags                        { get; }
		IHintsService                             Hints                             { get; }
		II18NService                              I18N                              { get; }
		IInboundEmailMessagesService              InboundEmailMessages              { get; }
		IInformationNotesService                  InformationNotes                  { get; }
		IInfrastructureService                    Infrastructure                    { get; }
		IInterestsService                         Interests                         { get; }
		IInvitedService                           Invited                           { get; }
		IJobService                               Job                               { get; }
		ILikesService                             Likes                             { get; }
		ILinksService                             Links                             { get; }
		IListsService                             Lists                             { get; }
		ILiveService                              Live                              { get; }
		ILostItemsService                         LostItems                         { get; }
		IMembersService                           Members                           { get; }
		IMenusPlanningService                     MenusPlanning                     { get; }
		IMenusService                             Menus                             { get; }
		INetworksService                          Networks                          { get; }
		INotificationsService                     Notifications                     { get; }
		INumbersService                           Numbers                           { get; }
		IPartnerResourcesService                  PartnerResources                  { get; }
		IPeopleService                            People                            { get; }
		IPeoplesInterestsService                  PeoplesInterests                  { get; }
		IPeoplesRecreationsService                PeoplesRecreations                { get; }
		IPeoplesSkillsService                     PeoplesSkills                     { get; }
		IPeopleVisitsService                      PeopleVisits                      { get; }
		IPicturesService                          Pictures                          { get; }
		IPlacesCategoriesService                  PlacesCategories                  { get; }
		IPlacesHistoryService                     PlacesHistory                     { get; }
		IPlacesService                            Places                            { get; }
		IPollsAnswersService                      PollsAnswers                      { get; }
		IPollsChoicesService                      PollsChoices                      { get; }
		IPollsService                             Polls                             { get; }
		IPrivateMessageService                    PrivateMessage                    { get; }
		IProfileFieldsService                     ProfileFields                     { get; }
		IProjectsMembersService                   ProjectsMembers                   { get; }
		IProjectsService                          Projects                          { get; }
		IRecreationsService                       Recreations                       { get; }
		IRegisterRequestsService                  RegisterRequests                  { get; }
		IRelationshipService                      Relationship                      { get; }
		IRequestsForProposalService               RequestsForProposal               { get; }
		IResumeSkillsService                      ResumeSkills                      { get; }
		IResumesService                           Resumes                           { get; }
		ISeekFriendsService                       SeekFriends                       { get; }
		ISkillsService                            Skills                            { get; }
		ISocialNetworkCompanySubscriptionsService SocialNetworkCompanySubscriptions { get; }
		ISocialNetworkConnectionsService          SocialNetworkConnections          { get; }
		ISocialNetworkStatesService               SocialNetworkStates               { get; }
		ISocialNetworkUserSubscriptionsService    SocialNetworkUserSubscriptions    { get; }
		IStatsCountersService                     StatsCounters                     { get; }
		ISubscriptionsService                     Subscriptions                     { get; }
		ISubscriptionTemplatesService             SubscriptionTemplates             { get; }
		ITagsService                              Tags                              { get; }
		ITeamsMembersService                      TeamsMembers                      { get; }
		ITeamsService                             Teams                             { get; }
		ITextService                              Text                              { get; }
		ITouchCommunicationItemsService           TouchCommunicationItems           { get; }
		ITouchCommunicationsService               TouchCommunications               { get; }
		IUserActionKeysService                    UserActionKeys                    { get; }
		IUserEmailChangeRequestService            UserEmailChangeRequest            { get; }
		IUserSettingsService                      UserSettings                      { get; }
		IWallCommentsService                      WallComments                      { get; }
		IWallService                              Wall                              { get; }
    }
}

namespace Sparkle.Services.Networks.Mocks
{
    using System;
    using Sparkle.Infrastructure;
    using Sparkle.Data.Networks;
    using Sparkle.Services;
    using Sparkle.Services.Networks;
    using Sparkle.UI;

    public partial class BasicServiceFactory
    {
		public HostingEnvironment                        HostingEnvironment                { get; set; }
		public Strings                                   Lang                              { get; set; }
		public ILogger                                   Logger                            { get; set; }
		public IEmailTemplateProvider                    EmailTemplateProvider             { get; set; }
		public IRepositoryFactory                        Repositories                      { get; set; }
		public Application                               Application                       { get; set; }
		public AppConfiguration                          AppConfiguration                  { get; set; }

		public IAchievementsCompanyService               AchievementsCompany               { get; set; }
		public IAchievementsService                      Achievements                      { get; set; }
		public IAchievementsUsersService                 AchievementsUsers                 { get; set; }
		public IActivitiesService                        Activities                        { get; set; }
		public IAdsCategoriesService                     AdsCategories                     { get; set; }
		public IAdsService                               Ads                               { get; set; }
		public IAlbumsService                            Albums                            { get; set; }
		public IApiKeysService                           ApiKeys                           { get; set; }
		public IBuildingService                          Building                          { get; set; }
		public ICareerOpportunitiesService               CareerOpportunities               { get; set; }
		public IClubsService                             Clubs                             { get; set; }
		public ICompaniesVisitsService                   CompaniesVisits                   { get; set; }
		public ICompanyAdminService                      CompanyAdmin                      { get; set; }
		public ICompanyContactsService                   CompanyContacts                   { get; set; }
		public ICompanyRelationshipsService              CompanyRelationships              { get; set; }
		public ICompanyService                           Company                           { get; set; }
		public ICompanySkillsService                     CompanySkills                     { get; set; }
		public ICreateNetworkRequestsService             CreateNetworkRequests             { get; set; }
		public ICryptoService                            Crypto                            { get; set; }
		public IDeviceConfigurationService               DeviceConfiguration               { get; set; }
		public IDevicePlanningService                    DevicePlanning                    { get; set; }
		public IDevicesService                           Devices                           { get; set; }
		public IEmailMessagesService                     EmailMessages                     { get; set; }
		public IEmailService                             Email                             { get; set; }
		public IEventPublicMembersService                EventPublicMembers                { get; set; }
		public IEventsCategoriesService                  EventsCategories                  { get; set; }
		public IEventsMembersService                     EventsMembers                     { get; set; }
		public IEventsService                            Events                            { get; set; }
		public IExchangeMaterialsService                 ExchangeMaterials                 { get; set; }
		public IExchangeSkillsService                    ExchangeSkills                    { get; set; }
		public IExchangeSurfacesService                  ExchangeSurfaces                  { get; set; }
		public IFriendService                            Friend                            { get; set; }
		public IGroupsCategoriesService                  GroupsCategories                  { get; set; }
		public IGroupsMembersService                     GroupsMembers                     { get; set; }
		public IGroupsService                            Groups                            { get; set; }
		public IGroupsTagsService                        GroupsTags                        { get; set; }
		public IHintsService                             Hints                             { get; set; }
		public II18NService                              I18N                              { get; set; }
		public IInboundEmailMessagesService              InboundEmailMessages              { get; set; }
		public IInformationNotesService                  InformationNotes                  { get; set; }
		public IInfrastructureService                    Infrastructure                    { get; set; }
		public IInterestsService                         Interests                         { get; set; }
		public IInvitedService                           Invited                           { get; set; }
		public IJobService                               Job                               { get; set; }
		public ILikesService                             Likes                             { get; set; }
		public ILinksService                             Links                             { get; set; }
		public IListsService                             Lists                             { get; set; }
		public ILiveService                              Live                              { get; set; }
		public ILostItemsService                         LostItems                         { get; set; }
		public IMembersService                           Members                           { get; set; }
		public IMenusPlanningService                     MenusPlanning                     { get; set; }
		public IMenusService                             Menus                             { get; set; }
		public INetworksService                          Networks                          { get; set; }
		public INotificationsService                     Notifications                     { get; set; }
		public INumbersService                           Numbers                           { get; set; }
		public IPartnerResourcesService                  PartnerResources                  { get; set; }
		public IPeopleService                            People                            { get; set; }
		public IPeoplesInterestsService                  PeoplesInterests                  { get; set; }
		public IPeoplesRecreationsService                PeoplesRecreations                { get; set; }
		public IPeoplesSkillsService                     PeoplesSkills                     { get; set; }
		public IPeopleVisitsService                      PeopleVisits                      { get; set; }
		public IPicturesService                          Pictures                          { get; set; }
		public IPlacesCategoriesService                  PlacesCategories                  { get; set; }
		public IPlacesHistoryService                     PlacesHistory                     { get; set; }
		public IPlacesService                            Places                            { get; set; }
		public IPollsAnswersService                      PollsAnswers                      { get; set; }
		public IPollsChoicesService                      PollsChoices                      { get; set; }
		public IPollsService                             Polls                             { get; set; }
		public IPrivateMessageService                    PrivateMessage                    { get; set; }
		public IProfileFieldsService                     ProfileFields                     { get; set; }
		public IProjectsMembersService                   ProjectsMembers                   { get; set; }
		public IProjectsService                          Projects                          { get; set; }
		public IRecreationsService                       Recreations                       { get; set; }
		public IRegisterRequestsService                  RegisterRequests                  { get; set; }
		public IRelationshipService                      Relationship                      { get; set; }
		public IRequestsForProposalService               RequestsForProposal               { get; set; }
		public IResumeSkillsService                      ResumeSkills                      { get; set; }
		public IResumesService                           Resumes                           { get; set; }
		public ISeekFriendsService                       SeekFriends                       { get; set; }
		public ISkillsService                            Skills                            { get; set; }
		public ISocialNetworkCompanySubscriptionsService SocialNetworkCompanySubscriptions { get; set; }
		public ISocialNetworkConnectionsService          SocialNetworkConnections          { get; set; }
		public ISocialNetworkStatesService               SocialNetworkStates               { get; set; }
		public ISocialNetworkUserSubscriptionsService    SocialNetworkUserSubscriptions    { get; set; }
		public IStatsCountersService                     StatsCounters                     { get; set; }
		public ISubscriptionsService                     Subscriptions                     { get; set; }
		public ISubscriptionTemplatesService             SubscriptionTemplates             { get; set; }
		public ITagsService                              Tags                              { get; set; }
		public ITeamsMembersService                      TeamsMembers                      { get; set; }
		public ITeamsService                             Teams                             { get; set; }
		public ITextService                              Text                              { get; set; }
		public ITouchCommunicationItemsService           TouchCommunicationItems           { get; set; }
		public ITouchCommunicationsService               TouchCommunications               { get; set; }
		public IUserActionKeysService                    UserActionKeys                    { get; set; }
		public IUserEmailChangeRequestService            UserEmailChangeRequest            { get; set; }
		public IUserSettingsService                      UserSettings                      { get; set; }
		public IWallCommentsService                      WallComments                      { get; set; }
		public IWallService                              Wall                              { get; set; }
    }
}

