 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// solutionPath:            <solution>
// projectPath:             <solution>\Networks
// projectName:             Networks

namespace Sparkle.Services.Main.Networks
{
    using System;
	using Sparkle.Services.Networks;

    [System.Diagnostics.DebuggerStepThrough]
    public partial class MainServiceFactory : IServiceFactory
    {
        private IAchievementsCompanyService _AchievementsCompany;
        IAchievementsCompanyService IServiceFactory.AchievementsCompany { get { return this._AchievementsCompany ?? (this._AchievementsCompany = new AchievementsCompanyService(this.MySelf.Repositories, this)); } }

        private IAchievementsService _Achievements;
        IAchievementsService IServiceFactory.Achievements { get { return this._Achievements ?? (this._Achievements = new AchievementsService(this.MySelf.Repositories, this)); } }

        private IAchievementsUsersService _AchievementsUsers;
        IAchievementsUsersService IServiceFactory.AchievementsUsers { get { return this._AchievementsUsers ?? (this._AchievementsUsers = new AchievementsUsersService(this.MySelf.Repositories, this)); } }

        private IActivitiesService _Activities;
        IActivitiesService IServiceFactory.Activities { get { return this._Activities ?? (this._Activities = new ActivitiesService(this.MySelf.Repositories, this)); } }

        private IAdsCategoriesService _AdsCategories;
        IAdsCategoriesService IServiceFactory.AdsCategories { get { return this._AdsCategories ?? (this._AdsCategories = new AdsCategoriesService(this.MySelf.Repositories, this)); } }

        private IAdsService _Ads;
        IAdsService IServiceFactory.Ads { get { return this._Ads ?? (this._Ads = new AdsService(this.MySelf.Repositories, this)); } }

        private IApiKeysService _ApiKeys;
        IApiKeysService IServiceFactory.ApiKeys { get { return this._ApiKeys ?? (this._ApiKeys = new ApiKeysService(this.MySelf.Repositories, this)); } }

        private IBuildingService _Building;
        IBuildingService IServiceFactory.Building { get { return this._Building ?? (this._Building = new BuildingService(this.MySelf.Repositories, this)); } }

        private ICacheService _Cache;
        ICacheService IServiceFactory.Cache { get { return this._Cache ?? (this._Cache = new CacheService(this.MySelf.Repositories, this, this.cache)); } }

        private IClubsService _Clubs;
        IClubsService IServiceFactory.Clubs { get { return this._Clubs ?? (this._Clubs = new ClubsService(this.MySelf.Repositories, this)); } }

        private ICompaniesVisitsService _CompaniesVisits;
        ICompaniesVisitsService IServiceFactory.CompaniesVisits { get { return this._CompaniesVisits ?? (this._CompaniesVisits = new CompaniesVisitsService(this.MySelf.Repositories, this)); } }

        private ICompanyContactsService _CompanyContacts;
        ICompanyContactsService IServiceFactory.CompanyContacts { get { return this._CompanyContacts ?? (this._CompanyContacts = new CompanyContactsService(this.MySelf.Repositories, this)); } }

        private ICompanyRelationshipsService _CompanyRelationships;
        ICompanyRelationshipsService IServiceFactory.CompanyRelationships { get { return this._CompanyRelationships ?? (this._CompanyRelationships = new CompanyRelationshipsService(this.MySelf.Repositories, this)); } }

        private ICompanyService _Company;
        ICompanyService IServiceFactory.Company { get { return this._Company ?? (this._Company = new CompanyService(this.MySelf.Repositories, this)); } }

        private ICompanySkillsService _CompanySkills;
        ICompanySkillsService IServiceFactory.CompanySkills { get { return this._CompanySkills ?? (this._CompanySkills = new CompanySkillsService(this.MySelf.Repositories, this)); } }

        private ICreateNetworkRequestsService _CreateNetworkRequests;
        ICreateNetworkRequestsService IServiceFactory.CreateNetworkRequests { get { return this._CreateNetworkRequests ?? (this._CreateNetworkRequests = new CreateNetworkRequestsService(this.MySelf.Repositories, this)); } }

        private ICryptoService _Crypto;
        ICryptoService IServiceFactory.Crypto { get { return this._Crypto ?? (this._Crypto = new CryptoService(this.MySelf.Repositories, this)); } }

        private IDeviceConfigurationService _DeviceConfiguration;
        IDeviceConfigurationService IServiceFactory.DeviceConfiguration { get { return this._DeviceConfiguration ?? (this._DeviceConfiguration = new DeviceConfigurationService(this.MySelf.Repositories, this)); } }

        private IDevicePlanningService _DevicePlanning;
        IDevicePlanningService IServiceFactory.DevicePlanning { get { return this._DevicePlanning ?? (this._DevicePlanning = new DevicePlanningService(this.MySelf.Repositories, this)); } }

        private IDevicesService _Devices;
        IDevicesService IServiceFactory.Devices { get { return this._Devices ?? (this._Devices = new DevicesService(this.MySelf.Repositories, this)); } }

        private IEmailMessagesService _EmailMessages;
        IEmailMessagesService IServiceFactory.EmailMessages { get { return this._EmailMessages ?? (this._EmailMessages = new EmailMessagesService(this.MySelf.Repositories, this)); } }

        private IEmailService _Email;
        IEmailService IServiceFactory.Email { get { return this._Email ?? (this._Email = new EmailService(this.MySelf.Repositories, this)); } }

        private IEventPublicMembersService _EventPublicMembers;
        IEventPublicMembersService IServiceFactory.EventPublicMembers { get { return this._EventPublicMembers ?? (this._EventPublicMembers = new EventPublicMembersService(this.MySelf.Repositories, this)); } }

        private IEventsCategoriesService _EventsCategories;
        IEventsCategoriesService IServiceFactory.EventsCategories { get { return this._EventsCategories ?? (this._EventsCategories = new EventsCategoriesService(this.MySelf.Repositories, this)); } }

        private IEventsMembersService _EventsMembers;
        IEventsMembersService IServiceFactory.EventsMembers { get { return this._EventsMembers ?? (this._EventsMembers = new EventsMembersService(this.MySelf.Repositories, this)); } }

        private IEventsService _Events;
        IEventsService IServiceFactory.Events { get { return this._Events ?? (this._Events = new EventsService(this.MySelf.Repositories, this)); } }

        private IExchangeMaterialsService _ExchangeMaterials;
        IExchangeMaterialsService IServiceFactory.ExchangeMaterials { get { return this._ExchangeMaterials ?? (this._ExchangeMaterials = new ExchangeMaterialsService(this.MySelf.Repositories, this)); } }

        private IExchangeSkillsService _ExchangeSkills;
        IExchangeSkillsService IServiceFactory.ExchangeSkills { get { return this._ExchangeSkills ?? (this._ExchangeSkills = new ExchangeSkillsService(this.MySelf.Repositories, this)); } }

        private IExchangeSurfacesService _ExchangeSurfaces;
        IExchangeSurfacesService IServiceFactory.ExchangeSurfaces { get { return this._ExchangeSurfaces ?? (this._ExchangeSurfaces = new ExchangeSurfacesService(this.MySelf.Repositories, this)); } }

        private IFriendService _Friend;
        IFriendService IServiceFactory.Friend { get { return this._Friend ?? (this._Friend = new FriendService(this.MySelf.Repositories, this)); } }

        private IGroupsCategoriesService _GroupsCategories;
        IGroupsCategoriesService IServiceFactory.GroupsCategories { get { return this._GroupsCategories ?? (this._GroupsCategories = new GroupsCategoriesService(this.MySelf.Repositories, this)); } }

        private IGroupsMembersService _GroupsMembers;
        IGroupsMembersService IServiceFactory.GroupsMembers { get { return this._GroupsMembers ?? (this._GroupsMembers = new GroupsMembersService(this.MySelf.Repositories, this)); } }

        private IGroupsService _Groups;
        IGroupsService IServiceFactory.Groups { get { return this._Groups ?? (this._Groups = new GroupsService(this.MySelf.Repositories, this)); } }

        private IGroupsTagsService _GroupsTags;
        IGroupsTagsService IServiceFactory.GroupsTags { get { return this._GroupsTags ?? (this._GroupsTags = new GroupsTagsService(this.MySelf.Repositories, this)); } }

        private IHintsService _Hints;
        IHintsService IServiceFactory.Hints { get { return this._Hints ?? (this._Hints = new HintsService(this.MySelf.Repositories, this)); } }

        private II18NService _I18N;
        II18NService IServiceFactory.I18N { get { return this._I18N ?? (this._I18N = new I18NService(this.MySelf.Repositories, this)); } }

        private IInboundEmailMessagesService _InboundEmailMessages;
        IInboundEmailMessagesService IServiceFactory.InboundEmailMessages { get { return this._InboundEmailMessages ?? (this._InboundEmailMessages = new InboundEmailMessagesService(this.MySelf.Repositories, this)); } }

        private IInformationNotesService _InformationNotes;
        IInformationNotesService IServiceFactory.InformationNotes { get { return this._InformationNotes ?? (this._InformationNotes = new InformationNotesService(this.MySelf.Repositories, this)); } }

        private IInfrastructureService _Infrastructure;
        IInfrastructureService IServiceFactory.Infrastructure { get { return this._Infrastructure ?? (this._Infrastructure = new InfrastructureService(this.MySelf.Repositories, this)); } }

        private IInterestsService _Interests;
        IInterestsService IServiceFactory.Interests { get { return this._Interests ?? (this._Interests = new InterestsService(this.MySelf.Repositories, this)); } }

        private IInvitedService _Invited;
        IInvitedService IServiceFactory.Invited { get { return this._Invited ?? (this._Invited = new InvitedService(this.MySelf.Repositories, this)); } }

        private IJobService _Job;
        IJobService IServiceFactory.Job { get { return this._Job ?? (this._Job = new JobService(this.MySelf.Repositories, this)); } }

        private ILikesService _Likes;
        ILikesService IServiceFactory.Likes { get { return this._Likes ?? (this._Likes = new LikesService(this.MySelf.Repositories, this)); } }

        private ILiveService _Live;
        ILiveService IServiceFactory.Live { get { return this._Live ?? (this._Live = new LiveService(this.MySelf.Repositories, this)); } }

        private ILostItemsService _LostItems;
        ILostItemsService IServiceFactory.LostItems { get { return this._LostItems ?? (this._LostItems = new LostItemsService(this.MySelf.Repositories, this)); } }

        private INetworksService _Networks;
        INetworksService IServiceFactory.Networks { get { return this._Networks ?? (this._Networks = new NetworksService(this.MySelf.Repositories, this)); } }

        private INotificationsService _Notifications;
        INotificationsService IServiceFactory.Notifications { get { return this._Notifications ?? (this._Notifications = new NotificationsService(this.MySelf.Repositories, this)); } }

        private INumbersService _Numbers;
        INumbersService IServiceFactory.Numbers { get { return this._Numbers ?? (this._Numbers = new NumbersService(this.MySelf.Repositories, this)); } }

        private IPartnerResourcesService _PartnerResources;
        IPartnerResourcesService IServiceFactory.PartnerResources { get { return this._PartnerResources ?? (this._PartnerResources = new PartnerResourcesService(this.MySelf.Repositories, this)); } }

        private IPeopleService _People;
        IPeopleService IServiceFactory.People { get { return this._People ?? (this._People = new PeopleService(this.MySelf.Repositories, this)); } }

        private IPeoplesInterestsService _PeoplesInterests;
        IPeoplesInterestsService IServiceFactory.PeoplesInterests { get { return this._PeoplesInterests ?? (this._PeoplesInterests = new PeoplesInterestsService(this.MySelf.Repositories, this)); } }

        private IPeoplesRecreationsService _PeoplesRecreations;
        IPeoplesRecreationsService IServiceFactory.PeoplesRecreations { get { return this._PeoplesRecreations ?? (this._PeoplesRecreations = new PeoplesRecreationsService(this.MySelf.Repositories, this)); } }

        private IPeoplesSkillsService _PeoplesSkills;
        IPeoplesSkillsService IServiceFactory.PeoplesSkills { get { return this._PeoplesSkills ?? (this._PeoplesSkills = new PeoplesSkillsService(this.MySelf.Repositories, this)); } }

        private IPeopleVisitsService _PeopleVisits;
        IPeopleVisitsService IServiceFactory.PeopleVisits { get { return this._PeopleVisits ?? (this._PeopleVisits = new PeopleVisitsService(this.MySelf.Repositories, this)); } }

        private IPlacesCategoriesService _PlacesCategories;
        IPlacesCategoriesService IServiceFactory.PlacesCategories { get { return this._PlacesCategories ?? (this._PlacesCategories = new PlacesCategoriesService(this.MySelf.Repositories, this)); } }

        private IPlacesHistoryService _PlacesHistory;
        IPlacesHistoryService IServiceFactory.PlacesHistory { get { return this._PlacesHistory ?? (this._PlacesHistory = new PlacesHistoryService(this.MySelf.Repositories, this)); } }

        private IPlacesService _Places;
        IPlacesService IServiceFactory.Places { get { return this._Places ?? (this._Places = new PlacesService(this.MySelf.Repositories, this)); } }

        private IPrivateMessageService _PrivateMessage;
        IPrivateMessageService IServiceFactory.PrivateMessage { get { return this._PrivateMessage ?? (this._PrivateMessage = new PrivateMessageService(this.MySelf.Repositories, this)); } }

        private IProfileFieldsService _ProfileFields;
        IProfileFieldsService IServiceFactory.ProfileFields { get { return this._ProfileFields ?? (this._ProfileFields = new ProfileFieldsService(this.MySelf.Repositories, this)); } }

        private IRecreationsService _Recreations;
        IRecreationsService IServiceFactory.Recreations { get { return this._Recreations ?? (this._Recreations = new RecreationsService(this.MySelf.Repositories, this)); } }

        private IRegisterRequestsService _RegisterRequests;
        IRegisterRequestsService IServiceFactory.RegisterRequests { get { return this._RegisterRequests ?? (this._RegisterRequests = new RegisterRequestsService(this.MySelf.Repositories, this)); } }

        private IRelationshipService _Relationship;
        IRelationshipService IServiceFactory.Relationship { get { return this._Relationship ?? (this._Relationship = new RelationshipService(this.MySelf.Repositories, this)); } }

        private IRequestsForProposalService _RequestsForProposal;
        IRequestsForProposalService IServiceFactory.RequestsForProposal { get { return this._RequestsForProposal ?? (this._RequestsForProposal = new RequestsForProposalService(this.MySelf.Repositories, this)); } }

        private IResumeSkillsService _ResumeSkills;
        IResumeSkillsService IServiceFactory.ResumeSkills { get { return this._ResumeSkills ?? (this._ResumeSkills = new ResumeSkillsService(this.MySelf.Repositories, this)); } }

        private IResumesService _Resumes;
        IResumesService IServiceFactory.Resumes { get { return this._Resumes ?? (this._Resumes = new ResumesService(this.MySelf.Repositories, this)); } }

        private ISeekFriendsService _SeekFriends;
        ISeekFriendsService IServiceFactory.SeekFriends { get { return this._SeekFriends ?? (this._SeekFriends = new SeekFriendsService(this.MySelf.Repositories, this)); } }

        private ISkillsService _Skills;
        ISkillsService IServiceFactory.Skills { get { return this._Skills ?? (this._Skills = new SkillsService(this.MySelf.Repositories, this)); } }

        private ISocialNetworkCompanySubscriptionsService _SocialNetworkCompanySubscriptions;
        ISocialNetworkCompanySubscriptionsService IServiceFactory.SocialNetworkCompanySubscriptions { get { return this._SocialNetworkCompanySubscriptions ?? (this._SocialNetworkCompanySubscriptions = new SocialNetworkCompanySubscriptionsService(this.MySelf.Repositories, this)); } }

        private ISocialNetworkConnectionsService _SocialNetworkConnections;
        ISocialNetworkConnectionsService IServiceFactory.SocialNetworkConnections { get { return this._SocialNetworkConnections ?? (this._SocialNetworkConnections = new SocialNetworkConnectionsService(this.MySelf.Repositories, this)); } }

        private ISocialNetworkStatesService _SocialNetworkStates;
        ISocialNetworkStatesService IServiceFactory.SocialNetworkStates { get { return this._SocialNetworkStates ?? (this._SocialNetworkStates = new SocialNetworkStatesService(this.MySelf.Repositories, this)); } }

        private ISocialNetworkUserSubscriptionsService _SocialNetworkUserSubscriptions;
        ISocialNetworkUserSubscriptionsService IServiceFactory.SocialNetworkUserSubscriptions { get { return this._SocialNetworkUserSubscriptions ?? (this._SocialNetworkUserSubscriptions = new SocialNetworkUserSubscriptionsService(this.MySelf.Repositories, this)); } }

        private IStatsCountersService _StatsCounters;
        IStatsCountersService IServiceFactory.StatsCounters { get { return this._StatsCounters ?? (this._StatsCounters = new StatsCountersService(this.MySelf.Repositories, this)); } }

        private ISubscriptionsService _Subscriptions;
        ISubscriptionsService IServiceFactory.Subscriptions { get { return this._Subscriptions ?? (this._Subscriptions = new SubscriptionsService(this.MySelf.Repositories, this)); } }

        private ISubscriptionTemplatesService _SubscriptionTemplates;
        ISubscriptionTemplatesService IServiceFactory.SubscriptionTemplates { get { return this._SubscriptionTemplates ?? (this._SubscriptionTemplates = new SubscriptionTemplatesService(this.MySelf.Repositories, this)); } }

        private ITagsService _Tags;
        ITagsService IServiceFactory.Tags { get { return this._Tags ?? (this._Tags = new TagsService(this.MySelf.Repositories, this)); } }

        private ITeamsMembersService _TeamsMembers;
        ITeamsMembersService IServiceFactory.TeamsMembers { get { return this._TeamsMembers ?? (this._TeamsMembers = new TeamsMembersService(this.MySelf.Repositories, this)); } }

        private ITeamsService _Teams;
        ITeamsService IServiceFactory.Teams { get { return this._Teams ?? (this._Teams = new TeamsService(this.MySelf.Repositories, this)); } }

        private ITextService _Text;
        ITextService IServiceFactory.Text { get { return this._Text ?? (this._Text = new TextService(this.MySelf.Repositories, this)); } }

        private ITouchCommunicationItemsService _TouchCommunicationItems;
        ITouchCommunicationItemsService IServiceFactory.TouchCommunicationItems { get { return this._TouchCommunicationItems ?? (this._TouchCommunicationItems = new TouchCommunicationItemsService(this.MySelf.Repositories, this)); } }

        private ITouchCommunicationsService _TouchCommunications;
        ITouchCommunicationsService IServiceFactory.TouchCommunications { get { return this._TouchCommunications ?? (this._TouchCommunications = new TouchCommunicationsService(this.MySelf.Repositories, this)); } }

        private IUserActionKeysService _UserActionKeys;
        IUserActionKeysService IServiceFactory.UserActionKeys { get { return this._UserActionKeys ?? (this._UserActionKeys = new UserActionKeysService(this.MySelf.Repositories, this)); } }

        private IUserEmailChangeRequestService _UserEmailChangeRequest;
        IUserEmailChangeRequestService IServiceFactory.UserEmailChangeRequest { get { return this._UserEmailChangeRequest ?? (this._UserEmailChangeRequest = new UserEmailChangeRequestService(this.MySelf.Repositories, this)); } }

        private IUserSettingsService _UserSettings;
        IUserSettingsService IServiceFactory.UserSettings { get { return this._UserSettings ?? (this._UserSettings = new UserSettingsService(this.MySelf.Repositories, this)); } }

        private IWallCommentsService _WallComments;
        IWallCommentsService IServiceFactory.WallComments { get { return this._WallComments ?? (this._WallComments = new WallCommentsService(this.MySelf.Repositories, this)); } }

        private IWallService _Wall;
        IWallService IServiceFactory.Wall { get { return this._Wall ?? (this._Wall = new WallService(this.MySelf.Repositories, this)); } }

    }
}
