
CREATE TABLE [dbo].[Places] (
    [Id]              INT              IDENTITY (1, 1) NOT NULL,
    [CategoryId]      INT              NOT NULL,
    [Name]            NVARCHAR (80)    COLLATE French_CI_AI NOT NULL,
    [Alias]           NVARCHAR (80)    NOT NULL,
    [Description]     NVARCHAR(4000)   NULL,
    [Address]         NVARCHAR (100)   NULL,
    [ZipCode]         NVARCHAR (10)    NULL,
    [City]            NVARCHAR (50)    COLLATE French_CI_AI NULL,
    [Country]         NVARCHAR (50)    COLLATE French_CI_AI NULL,
    [Building]        NVARCHAR (50)    NULL,
    [Floor]           INT              NULL,
    [Access]          NVARCHAR (50)    NULL,
    [Door]            NVARCHAR (10)    NULL,
    [ParentId]        INT              NULL,
    [PeopleOwner]     UNIQUEIDENTIFIER NULL,
    [CompanyOwner]    INT              NULL,
    [Phone]           NVARCHAR (20)    NULL,
    [CreatedByUserId] INT              NOT NULL,
	[lat]			  FLOAT            NULL,
	[lon]			  FLOAT            NULL,
	[FoursquareId]	  NVARCHAR (30)    NULL,
	[NetworkId]   int            not null,
	[Main]   bit            not null default 0,
	[Geography]       GEOGRAPHY        NULL,

	--CONSTRAINT [UC_dbo_Places_Alias] UNIQUE ([Alias], [NetworkId]),
);
