CREATE TABLE [dbo].[Resumes] (
    [Id]               INT              IDENTITY (1, 1) NOT NULL,
	[NetworkId]        INT              NOT NULL,
	[FirstName]        NVARCHAR (100)   NOT NULL,
    [LastName]         NVARCHAR (100)   NOT NULL,
	[Gender]           INT              NOT NULL,
    [Birthday]         DATE             NULL,
    [Objective]        NVARCHAR(4000)   NOT NULL,
    [About]            NVARCHAR(4000)   NOT NULL,
	[Email]            NVARCHAR (100)   NOT NULL,
    [Phone]            NVARCHAR (100)   NOT NULL,
	[Picture]          NVARCHAR (40)    NULL,
	[ResumeUrl]        NVARCHAR (200)   NULL,
	[LinkedInUrl]      NVARCHAR (200)   NULL,
	[ViadeoUrl]        NVARCHAR (200)   NULL,
    [RequestType]      TINYINT			NOT NULL,
    [Pin]              NVARCHAR (4)     NOT NULL,
    [IsApproved]       BIT              NOT NULL DEFAULT 0,
    [IsActive]         BIT              NOT NULL DEFAULT 0,
	[CreatedDateUtc]   datetime         not null,
	[EditedDateUtc]    datetime         null,
);
