//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparkle.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sparkle.Services.Resources.GeneralMessages", typeof(GeneralMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string Desc_EmailAddress {
            get {
                return ResourceManager.GetString("Desc_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string Label_AddressAltitude {
            get {
                return ResourceManager.GetString("Label_AddressAltitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Label_AddressLatitude {
            get {
                return ResourceManager.GetString("Label_AddressLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Label_AddressLine1 {
            get {
                return ResourceManager.GetString("Label_AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (extension).
        /// </summary>
        public static string Label_AddressLine2 {
            get {
                return ResourceManager.GetString("Label_AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (extension 2).
        /// </summary>
        public static string Label_AddressLine3 {
            get {
                return ResourceManager.GetString("Label_AddressLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (extension 3).
        /// </summary>
        public static string Label_AddressLine4 {
            get {
                return ResourceManager.GetString("Label_AddressLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (extension 4).
        /// </summary>
        public static string Label_AddressLine5 {
            get {
                return ResourceManager.GetString("Label_AddressLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Label_AddressLongitude {
            get {
                return ResourceManager.GetString("Label_AddressLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Label_AddressRemark {
            get {
                return ResourceManager.GetString("Label_AddressRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Label_City {
            get {
                return ResourceManager.GetString("Label_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civility.
        /// </summary>
        public static string Label_Civility {
            get {
                return ResourceManager.GetString("Label_Civility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string Label_Culture {
            get {
                return ResourceManager.GetString("Label_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long description.
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string Label_DisplayName {
            get {
                return ResourceManager.GetString("Label_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Label_EmailAddress {
            get {
                return ResourceManager.GetString("Label_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Label_Firstname {
            get {
                return ResourceManager.GetString("Label_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark for staff.
        /// </summary>
        public static string Label_InternalRemark {
            get {
                return ResourceManager.GetString("Label_InternalRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is deleted.
        /// </summary>
        public static string Label_IsDeleted {
            get {
                return ResourceManager.GetString("Label_IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is enabled.
        /// </summary>
        public static string Label_IsEnabled {
            get {
                return ResourceManager.GetString("Label_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string Label_IsMinor {
            get {
                return ResourceManager.GetString("Label_IsMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Label_Lastname {
            get {
                return ResourceManager.GetString("Label_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Label_PhoneNumber {
            get {
                return ResourceManager.GetString("Label_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Label_Price {
            get {
                return ResourceManager.GetString("Label_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (with taxes included).
        /// </summary>
        public static string Label_PriceIT {
            get {
                return ResourceManager.GetString("Label_PriceIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (without taxes).
        /// </summary>
        public static string Label_PriceWT {
            get {
                return ResourceManager.GetString("Label_PriceWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short description.
        /// </summary>
        public static string Label_ShortDescription {
            get {
                return ResourceManager.GetString("Label_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Label_SortOrder {
            get {
                return ResourceManager.GetString("Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State or region.
        /// </summary>
        public static string Label_State {
            get {
                return ResourceManager.GetString("Label_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string Label_Timezone {
            get {
                return ResourceManager.GetString("Label_Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Label_Username {
            get {
                return ResourceManager.GetString("Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Label_Visible {
            get {
                return ResourceManager.GetString("Label_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL.
        /// </summary>
        public static string Label_Website {
            get {
                return ResourceManager.GetString("Label_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string Label_ZipCode {
            get {
                return ResourceManager.GetString("Label_ZipCode", resourceCulture);
            }
        }
    }
}
