//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Sparkle.Entities.Networks.Neutral
{
    public partial class CompanyTagPoco
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public int CompanyId
        {
            get { return _companyId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (this._companyId != value)
                    {
                        if (this.Company != null && this.Company.ID != value)
                        {
                            this.Company = null;
                        }
                        this._companyId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _companyId;
    
        public int TagId
        {
            get { return _tagId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (this._tagId != value)
                    {
                        if (this.TagDefinition != null && this.TagDefinition.Id != value)
                        {
                            this.TagDefinition = null;
                        }
                        this._tagId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _tagId;
    
        public System.DateTime DateCreatedUtc
        {
            get;
            set;
        }
    
        public int CreatedByUserId
        {
            get { return _createdByUserId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (this._createdByUserId != value)
                    {
                        if (this.CreatedByUser != null && this.CreatedByUser.Id != value)
                        {
                            this.CreatedByUser = null;
                        }
                        this._createdByUserId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _createdByUserId;
    
        public Nullable<System.DateTime> DateDeletedUtc
        {
            get;
            set;
        }
    
        public Nullable<int> DeletedByUserId
        {
            get { return _deletedByUserId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (this._deletedByUserId != value)
                    {
                        if (this.DeletedByUser != null && this.DeletedByUser.Id != value)
                        {
                            this.DeletedByUser = null;
                        }
                        this._deletedByUserId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _deletedByUserId;
    
        public Nullable<byte> DeleteReason
        {
            get;
            set;
        }
    
        public int SortOrder
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual CompanyPoco Company
        {
            get { return _company; }
            set
            {
                if (!ReferenceEquals(_company, value))
                {
                    var previousValue = _company;
                    _company = value;
                    FixupCompany(previousValue);
                }
            }
        }
        private CompanyPoco _company;
    
        public virtual UserPoco CreatedByUser
        {
            get { return _createdByUser; }
            set
            {
                if (!ReferenceEquals(_createdByUser, value))
                {
                    var previousValue = _createdByUser;
                    _createdByUser = value;
                    FixupCreatedByUser(previousValue);
                }
            }
        }
        private UserPoco _createdByUser;
    
        public virtual UserPoco DeletedByUser
        {
            get { return _deletedByUser; }
            set
            {
                if (!ReferenceEquals(_deletedByUser, value))
                {
                    var previousValue = _deletedByUser;
                    _deletedByUser = value;
                    FixupDeletedByUser(previousValue);
                }
            }
        }
        private UserPoco _deletedByUser;
    
        public virtual TagDefinitionPoco TagDefinition
        {
            get { return _tagDefinition; }
            set
            {
                if (!ReferenceEquals(_tagDefinition, value))
                {
                    var previousValue = _tagDefinition;
                    _tagDefinition = value;
                    FixupTagDefinition(previousValue);
                }
            }
        }
        private TagDefinitionPoco _tagDefinition;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCompany(CompanyPoco previousValue)
        {
            if (previousValue != null && previousValue.Tags.Contains(this))
            {
                previousValue.Tags.Remove(this);
            }
    
            if (Company != null)
            {
                if (!Company.Tags.Contains(this))
                {
                    Company.Tags.Add(this);
                }
                if (CompanyId != Company.ID)
                {
                    CompanyId = Company.ID;
                }
            }
        }
    
        private void FixupCreatedByUser(UserPoco previousValue)
        {
            if (previousValue != null && previousValue.CreatedCompanyTags.Contains(this))
            {
                previousValue.CreatedCompanyTags.Remove(this);
            }
    
            if (CreatedByUser != null)
            {
                if (!CreatedByUser.CreatedCompanyTags.Contains(this))
                {
                    CreatedByUser.CreatedCompanyTags.Add(this);
                }
                if (CreatedByUserId != CreatedByUser.Id)
                {
                    CreatedByUserId = CreatedByUser.Id;
                }
            }
        }
    
        private void FixupDeletedByUser(UserPoco previousValue)
        {
            if (previousValue != null && previousValue.DeletedCompanyTags.Contains(this))
            {
                previousValue.DeletedCompanyTags.Remove(this);
            }
    
            if (DeletedByUser != null)
            {
                if (!DeletedByUser.DeletedCompanyTags.Contains(this))
                {
                    DeletedByUser.DeletedCompanyTags.Add(this);
                }
                if (DeletedByUserId != DeletedByUser.Id)
                {
                    DeletedByUserId = DeletedByUser.Id;
                }
            }
            else if (!_settingFK)
            {
                DeletedByUserId = null;
            }
        }
    
        private void FixupTagDefinition(TagDefinitionPoco previousValue)
        {
            if (previousValue != null && previousValue.CompanyTags.Contains(this))
            {
                previousValue.CompanyTags.Remove(this);
            }
    
            if (TagDefinition != null)
            {
                if (!TagDefinition.CompanyTags.Contains(this))
                {
                    TagDefinition.CompanyTags.Add(this);
                }
                if (TagId != TagDefinition.Id)
                {
                    TagId = TagDefinition.Id;
                }
            }
        }

        #endregion

    }
}
