//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Sparkle.Entities.Networks.Neutral
{
    public partial class ContactPoco
    {
        #region Primitive Properties
    
        public Nullable<bool> IsDisplayed
        {
            get;
            set;
        }
    
        public int UserId
        {
            get { return _userId; }
            set
            {
                if (this._userId != value)
                {
                    if (this.User != null && this.User.Id != value)
                    {
                        this.User = null;
                    }
                    this._userId = value;
                }
            }
        }
        private int _userId;
    
        public int ContactId
        {
            get { return _contactId; }
            set
            {
                if (this._contactId != value)
                {
                    if (this.UserProfile != null && this.UserProfile.Id != value)
                    {
                        this.UserProfile = null;
                    }
                    this._contactId = value;
                }
            }
        }
        private int _contactId;

        #endregion

        #region Navigation Properties
    
        public virtual UserPoco UserProfile
        {
            get { return _userProfile; }
            set
            {
                if (!ReferenceEquals(_userProfile, value))
                {
                    var previousValue = _userProfile;
                    _userProfile = value;
                    FixupUserProfile(previousValue);
                }
            }
        }
        private UserPoco _userProfile;
    
        public virtual UserPoco User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private UserPoco _user;

        #endregion

        #region Association Fixup
    
        private void FixupUserProfile(UserPoco previousValue)
        {
            if (previousValue != null && previousValue.ContactsOf.Contains(this))
            {
                previousValue.ContactsOf.Remove(this);
            }
    
            if (UserProfile != null)
            {
                if (!UserProfile.ContactsOf.Contains(this))
                {
                    UserProfile.ContactsOf.Add(this);
                }
                if (ContactId != UserProfile.Id)
                {
                    ContactId = UserProfile.Id;
                }
            }
        }
    
        private void FixupUser(UserPoco previousValue)
        {
            if (previousValue != null && previousValue.Contacts.Contains(this))
            {
                previousValue.Contacts.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Contacts.Contains(this))
                {
                    User.Contacts.Add(this);
                }
                if (UserId != User.Id)
                {
                    UserId = User.Id;
                }
            }
        }

        #endregion

    }
}
