//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Sparkle.Entities.Networks.Neutral
{
    public partial class DevicePoco
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public System.Guid DeviceId
        {
            get;
            set;
        }
    
        public string Name
        {
            get;
            set;
        }
    
        public System.DateTime FirstStartDateUtc
        {
            get;
            set;
        }
    
        public System.DateTime LastActivityDateUtc
        {
            get;
            set;
        }
    
        public string Version
        {
            get;
            set;
        }
    
        public string Type
        {
            get;
            set;
        }
    
        public string DefaultLayout
        {
            get;
            set;
        }
    
        public string DefaultLayoutData
        {
            get;
            set;
        }
    
        public Nullable<int> PlaceId
        {
            get;
            set;
        }
    
        public int NetworkId
        {
            get { return _networkId; }
            set
            {
                if (this._networkId != value)
                {
                    if (this.Network != null && this.Network.Id != value)
                    {
                        this.Network = null;
                    }
                    this._networkId = value;
                }
            }
        }
        private int _networkId;

        #endregion

        #region Navigation Properties
    
        // DevicePlanning
        public ICollection<DevicePlanningPoco> DevicePlannings
        {
            get
            {
                if (_devicePlannings == null)
                {
                    var newCollection = new FixupCollection<DevicePlanningPoco>();
                    newCollection.CollectionChanged += FixupDevicePlannings;
                    _devicePlannings = newCollection;
                }
                return _devicePlannings;
            }
            set
            {
                if (!ReferenceEquals(_devicePlannings, value))
                {
                    var previousValue = _devicePlannings as FixupCollection<DevicePlanningPoco>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupDevicePlannings;
                    }
                    _devicePlannings = value;
                    var newValue = value as FixupCollection<DevicePlanningPoco>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupDevicePlannings;
                    }
                }
            }
        }
        private ICollection<DevicePlanningPoco> _devicePlannings;
    
        public virtual NetworkPoco Network
        {
            get { return _network; }
            set
            {
                if (!ReferenceEquals(_network, value))
                {
                    var previousValue = _network;
                    _network = value;
                    FixupNetwork(previousValue);
                }
            }
        }
        private NetworkPoco _network;

        #endregion

        #region Association Fixup
    
        private void FixupNetwork(NetworkPoco previousValue)
        {
            if (previousValue != null && previousValue.Devices.Contains(this))
            {
                previousValue.Devices.Remove(this);
            }
    
            if (Network != null)
            {
                if (!Network.Devices.Contains(this))
                {
                    Network.Devices.Add(this);
                }
                if (NetworkId != Network.Id)
                {
                    NetworkId = Network.Id;
                }
            }
        }
    
        private void FixupDevicePlannings(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (DevicePlanningPoco item in e.NewItems)
                {
                    item.Device = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (DevicePlanningPoco item in e.OldItems)
                {
                    if (ReferenceEquals(item.Device, this))
                    {
                        item.Device = null;
                    }
                }
            }
        }

        #endregion

    }
}
