//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Sparkle.Entities.Networks.Neutral
{
    public partial class JobByBusinessPoco
    {
        #region Primitive Properties
    
        public int JobId
        {
            get { return _jobId; }
            set
            {
                if (this._jobId != value)
                {
                    if (this.Job != null && this.Job.Id != value)
                    {
                        this.Job = null;
                    }
                    this._jobId = value;
                }
            }
        }
        private int _jobId;
    
        public int BusinessId
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual JobPoco Job
        {
            get { return _job; }
            set
            {
                if (!ReferenceEquals(_job, value))
                {
                    var previousValue = _job;
                    _job = value;
                    FixupJob(previousValue);
                }
            }
        }
        private JobPoco _job;

        #endregion

        #region Association Fixup
    
        private void FixupJob(JobPoco previousValue)
        {
            if (previousValue != null && previousValue.JobByBusinesses.Contains(this))
            {
                previousValue.JobByBusinesses.Remove(this);
            }
    
            if (Job != null)
            {
                if (!Job.JobByBusinesses.Contains(this))
                {
                    Job.JobByBusinesses.Add(this);
                }
                if (JobId != Job.Id)
                {
                    JobId = Job.Id;
                }
            }
        }

        #endregion

    }
}
