//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Sparkle.Entities.Networks.Neutral
{
    public partial class PlaceProfileFieldPoco
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public int PlaceId
        {
            get { return _placeId; }
            set
            {
                if (this._placeId != value)
                {
                    if (this.Place != null && this.Place.Id != value)
                    {
                        this.Place = null;
                    }
                    this._placeId = value;
                }
            }
        }
        private int _placeId;
    
        public int ProfileFieldId
        {
            get { return _profileFieldId; }
            set
            {
                if (this._profileFieldId != value)
                {
                    if (this.ProfileField != null && this.ProfileField.Id != value)
                    {
                        this.ProfileField = null;
                    }
                    this._profileFieldId = value;
                }
            }
        }
        private int _profileFieldId;
    
        public string Value
        {
            get;
            set;
        }
    
        public System.DateTime DateCreatedUtc
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> DateUpdatedUtc
        {
            get;
            set;
        }
    
        public short UpdateCount
        {
            get;
            set;
        }
    
        public byte Source
        {
            get;
            set;
        }
    
        public string Data
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual PlacePoco Place
        {
            get { return _place; }
            set
            {
                if (!ReferenceEquals(_place, value))
                {
                    var previousValue = _place;
                    _place = value;
                    FixupPlace(previousValue);
                }
            }
        }
        private PlacePoco _place;
    
        public virtual ProfileFieldPoco ProfileField
        {
            get { return _profileField; }
            set
            {
                if (!ReferenceEquals(_profileField, value))
                {
                    var previousValue = _profileField;
                    _profileField = value;
                    FixupProfileField(previousValue);
                }
            }
        }
        private ProfileFieldPoco _profileField;

        #endregion

        #region Association Fixup
    
        private void FixupPlace(PlacePoco previousValue)
        {
            if (previousValue != null && previousValue.PlaceProfileFields.Contains(this))
            {
                previousValue.PlaceProfileFields.Remove(this);
            }
    
            if (Place != null)
            {
                if (!Place.PlaceProfileFields.Contains(this))
                {
                    Place.PlaceProfileFields.Add(this);
                }
                if (PlaceId != Place.Id)
                {
                    PlaceId = Place.Id;
                }
            }
        }
    
        private void FixupProfileField(ProfileFieldPoco previousValue)
        {
            if (previousValue != null && previousValue.PlaceProfileFields.Contains(this))
            {
                previousValue.PlaceProfileFields.Remove(this);
            }
    
            if (ProfileField != null)
            {
                if (!ProfileField.PlaceProfileFields.Contains(this))
                {
                    ProfileField.PlaceProfileFields.Add(this);
                }
                if (ProfileFieldId != ProfileField.Id)
                {
                    ProfileFieldId = ProfileField.Id;
                }
            }
        }

        #endregion

    }
}
