//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Sparkle.Entities.Networks.Neutral
{
    public partial class RequestForProposalPoco
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public string CompanySector
        {
            get;
            set;
        }
    
        public string CompanyName
        {
            get;
            set;
        }
    
        public string CompanyEmail
        {
            get;
            set;
        }
    
        public string CompanyPhoneNumber
        {
            get;
            set;
        }
    
        public string Category
        {
            get;
            set;
        }
    
        public string Description
        {
            get;
            set;
        }
    
        public Nullable<int> MinBudget
        {
            get;
            set;
        }
    
        public Nullable<int> MaxBudget
        {
            get;
            set;
        }
    
        public System.DateTime Date
        {
            get;
            set;
        }
    
        public System.DateTime Deadline
        {
            get;
            set;
        }
    
        public int NetworkId
        {
            get { return _networkId; }
            set
            {
                if (this._networkId != value)
                {
                    if (this.Network != null && this.Network.Id != value)
                    {
                        this.Network = null;
                    }
                    this._networkId = value;
                }
            }
        }
        private int _networkId;

        #endregion

        #region Navigation Properties
    
        public virtual NetworkPoco Network
        {
            get { return _network; }
            set
            {
                if (!ReferenceEquals(_network, value))
                {
                    var previousValue = _network;
                    _network = value;
                    FixupNetwork(previousValue);
                }
            }
        }
        private NetworkPoco _network;

        #endregion

        #region Association Fixup
    
        private void FixupNetwork(NetworkPoco previousValue)
        {
            if (previousValue != null && previousValue.RequestsForProposals.Contains(this))
            {
                previousValue.RequestsForProposals.Remove(this);
            }
    
            if (Network != null)
            {
                if (!Network.RequestsForProposals.Contains(this))
                {
                    Network.RequestsForProposals.Add(this);
                }
                if (NetworkId != Network.Id)
                {
                    NetworkId = Network.Id;
                }
            }
        }

        #endregion

    }
}
