//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Sparkle.Entities.Networks.Neutral
{
    public partial class UserInterestPoco
    {
        #region Primitive Properties
    
        public int Id
        {
            get;
            set;
        }
    
        public int InterestId
        {
            get { return _interestId; }
            set
            {
                if (this._interestId != value)
                {
                    if (this.Interest != null && this.Interest.Id != value)
                    {
                        this.Interest = null;
                    }
                    this._interestId = value;
                }
            }
        }
        private int _interestId;
    
        public System.DateTime Date
        {
            get;
            set;
        }
    
        public int UserId
        {
            get { return _userId; }
            set
            {
                if (this._userId != value)
                {
                    if (this.User != null && this.User.Id != value)
                    {
                        this.User = null;
                    }
                    this._userId = value;
                }
            }
        }
        private int _userId;

        #endregion

        #region Navigation Properties
    
        public virtual InterestPoco Interest
        {
            get { return _interest; }
            set
            {
                if (!ReferenceEquals(_interest, value))
                {
                    var previousValue = _interest;
                    _interest = value;
                    FixupInterest(previousValue);
                }
            }
        }
        private InterestPoco _interest;
    
        public virtual UserPoco User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private UserPoco _user;

        #endregion

        #region Association Fixup
    
        private void FixupInterest(InterestPoco previousValue)
        {
            if (previousValue != null && previousValue.UserInterests.Contains(this))
            {
                previousValue.UserInterests.Remove(this);
            }
    
            if (Interest != null)
            {
                if (!Interest.UserInterests.Contains(this))
                {
                    Interest.UserInterests.Add(this);
                }
                if (InterestId != Interest.Id)
                {
                    InterestId = Interest.Id;
                }
            }
        }
    
        private void FixupUser(UserPoco previousValue)
        {
            if (previousValue != null && previousValue.UserInterests.Contains(this))
            {
                previousValue.UserInterests.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.UserInterests.Contains(this))
                {
                    User.UserInterests.Add(this);
                }
                if (UserId != User.Id)
                {
                    UserId = User.Id;
                }
            }
        }

        #endregion

    }
}
