//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sparkle.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sparkle.Common.Resources.MainStrings", typeof(MainStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t like anymore.
        /// </summary>
        public static string Dislike {
            get {
                return ResourceManager.GetString("Dislike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string DurationUnit_Day {
            get {
                return ResourceManager.GetString("DurationUnit_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string DurationUnit_Day_Plural {
            get {
                return ResourceManager.GetString("DurationUnit_Day_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string DurationUnit_Hour {
            get {
                return ResourceManager.GetString("DurationUnit_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string DurationUnit_Hour_Plural {
            get {
                return ResourceManager.GetString("DurationUnit_Hour_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millisecond.
        /// </summary>
        public static string DurationUnit_Millisecond {
            get {
                return ResourceManager.GetString("DurationUnit_Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        public static string DurationUnit_Millisecond_Plural {
            get {
                return ResourceManager.GetString("DurationUnit_Millisecond_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string DurationUnit_Minute {
            get {
                return ResourceManager.GetString("DurationUnit_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string DurationUnit_Minute_Plural {
            get {
                return ResourceManager.GetString("DurationUnit_Minute_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        public static string DurationUnit_Month {
            get {
                return ResourceManager.GetString("DurationUnit_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        public static string DurationUnit_Month_Plural {
            get {
                return ResourceManager.GetString("DurationUnit_Month_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nanosecond.
        /// </summary>
        public static string DurationUnit_Nanosecond {
            get {
                return ResourceManager.GetString("DurationUnit_Nanosecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nanoseconds.
        /// </summary>
        public static string DurationUnit_Nanosecond_Plural {
            get {
                return ResourceManager.GetString("DurationUnit_Nanosecond_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        public static string DurationUnit_Second {
            get {
                return ResourceManager.GetString("DurationUnit_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string DurationUnit_Second_Plural {
            get {
                return ResourceManager.GetString("DurationUnit_Second_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string DurationUnit_Week {
            get {
                return ResourceManager.GetString("DurationUnit_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string DurationUnit_Week_Plural {
            get {
                return ResourceManager.GetString("DurationUnit_Week_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string DurationUnit_Year {
            get {
                return ResourceManager.GetString("DurationUnit_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string DurationUnit_Year_Plural {
            get {
                return ResourceManager.GetString("DurationUnit_Year_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this afternoon.
        /// </summary>
        public static string NiceDateTime_Afternoon {
            get {
                return ResourceManager.GetString("NiceDateTime_Afternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} days ago.
        /// </summary>
        public static string NiceDateTime_DaysAgo_ {
            get {
                return ResourceManager.GetString("NiceDateTime_DaysAgo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this evening.
        /// </summary>
        public static string NiceDateTime_Evening {
            get {
                return ResourceManager.GetString("NiceDateTime_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} hours ago.
        /// </summary>
        public static string NiceDateTime_HoursAgo_ {
            get {
                return ResourceManager.GetString("NiceDateTime_HoursAgo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0:0} days.
        /// </summary>
        public static string NiceDateTime_InDays_ {
            get {
                return ResourceManager.GetString("NiceDateTime_InDays_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0:0} hours.
        /// </summary>
        public static string NiceDateTime_InHours_ {
            get {
                return ResourceManager.GetString("NiceDateTime_InHours_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0:0} minutes.
        /// </summary>
        public static string NiceDateTime_InMinutes_ {
            get {
                return ResourceManager.GetString("NiceDateTime_InMinutes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0:0} months.
        /// </summary>
        public static string NiceDateTime_InMonths_ {
            get {
                return ResourceManager.GetString("NiceDateTime_InMonths_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in 1 hour.
        /// </summary>
        public static string NiceDateTime_InOneHour {
            get {
                return ResourceManager.GetString("NiceDateTime_InOneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in {0:0} years.
        /// </summary>
        public static string NiceDateTime_InYears_ {
            get {
                return ResourceManager.GetString("NiceDateTime_InYears_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string NiceDateTime_JustNow {
            get {
                return ResourceManager.GetString("NiceDateTime_JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last night.
        /// </summary>
        public static string NiceDateTime_LastNight {
            get {
                return ResourceManager.GetString("NiceDateTime_LastNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to during midday.
        /// </summary>
        public static string NiceDateTime_Midday {
            get {
                return ResourceManager.GetString("NiceDateTime_Midday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} minutes ago.
        /// </summary>
        public static string NiceDateTime_MinutesAgo_ {
            get {
                return ResourceManager.GetString("NiceDateTime_MinutesAgo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} months ago.
        /// </summary>
        public static string NiceDateTime_MonthsAgo_ {
            get {
                return ResourceManager.GetString("NiceDateTime_MonthsAgo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this morning.
        /// </summary>
        public static string NiceDateTime_Morning {
            get {
                return ResourceManager.GetString("NiceDateTime_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next month.
        /// </summary>
        public static string NiceDateTime_NextMonth {
            get {
                return ResourceManager.GetString("NiceDateTime_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next year.
        /// </summary>
        public static string NiceDateTime_NextYear {
            get {
                return ResourceManager.GetString("NiceDateTime_NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one hour ago.
        /// </summary>
        public static string NiceDateTime_OneHourAgo {
            get {
                return ResourceManager.GetString("NiceDateTime_OneHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        public static string NiceDateTime_PreviousMonth {
            get {
                return ResourceManager.GetString("NiceDateTime_PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last year.
        /// </summary>
        public static string NiceDateTime_PreviousYear {
            get {
                return ResourceManager.GetString("NiceDateTime_PreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string NiceDateTime_Tomorrow {
            get {
                return ResourceManager.GetString("NiceDateTime_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tonight.
        /// </summary>
        public static string NiceDateTime_Tonight {
            get {
                return ResourceManager.GetString("NiceDateTime_Tonight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} years ago.
        /// </summary>
        public static string NiceDateTime_YearsAgo_ {
            get {
                return ResourceManager.GetString("NiceDateTime_YearsAgo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string NiceDateTime_Yesterday {
            get {
                return ResourceManager.GetString("NiceDateTime_Yesterday", resourceCulture);
            }
        }
    }
}
