ALTER TABLE [dbo].[TeamMembers]
    ADD CONSTRAINT [PK_eura_TeamsMembers_1] PRIMARY KEY CLUSTERED ([TeamId] ASC, [UserId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

