ALTER TABLE [dbo].[JobByBusiness]
    ADD CONSTRAINT [PK_JobByBusiness] PRIMARY KEY CLUSTERED ([JobId] ASC, [BusinessId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

